### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by studentNixe** [annemodd/SaltbaeProjekt#41]
- [ ] catch errors
- [ ] share post on fb troubles
- [ ] check data upload with js (client)
- [ ] /about content + design
- [ ] category filter
- [ ] css hashtags not responsive
- [ ] look over design
- [ ] documentation
